### ISSUE TITLE
Postgres - Editing a record

### ISSUE THREAD

**Issue by anupsaund** [strongloop/loopback-example-offline-sync#56]
Editing a Todo - creates an index violation as it tries to add the same record into my Todo table.

See attached screenshot...

![capture](https://cloud.githubusercontent.com/assets/6728822/6555006/78dc7fca-c659-11e4-96ac-3cc129095169.PNG)

-- Table: todo

CREATE TABLE todo
(
  title text,
  completed boolean,
  created double precision,
  id text NOT NULL,
  CONSTRAINT pkid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE todo
  OWNER TO postgres;

**Comment by bajtos** [comment]
This is most likely a bug in the replication algorithm that have been fixed on loopback master. We should verify after a new version of the following modules was released: loopback, loopback-datasource-juggler, loopback-connector-postgresql.

**Comment by bajtos** [comment]
See https://github.com/strongloop/loopback/pull/973.

**Comment by anupsaund** [comment]
@bajtos I implemented https://github.com/strongloop/loopback/pull/973 and it fixed the errors.

**Comment by bajtos** [comment]
This should be fixed in `loopback@2.15.0` and `loopback-connector-postgresql@1.7.0`.
