### ISSUE TITLE
Mssql - error when creating a Todo

### ISSUE THREAD

**Issue by anupsaund** [strongloop/loopback-example-offline-sync#57]
From within the loopback-example-full-stack.

npm install loopback-connector-mssql.

Set up datasources with a new mssql connection.

Change model config for Todo to use mssql.

slc arc - then migrate the Todo model into sql server.

grunt serve

Attempt to add a Todo... todo sync fails...

On /api/Todos/bulk-update
"conversion failed when converting from a character string to uniqueidentifier"

See attached screenshot.

![capture](https://cloud.githubusercontent.com/assets/6728822/6558984/8d9bd4f6-c677-11e4-8a7d-dd28e98ce52c.PNG)

**Comment by ritch** [comment]
@anupsaund are you still seeing this? Please ping me and Ill re-open.
