### ISSUE TITLE
Uncaught TypeError: Cannot read property 'seq' of undefined

### ISSUE THREAD

**Issue by osxi** [strongloop/loopback-example-offline-sync#61]
While "connected," I get "isConnected? true" in the Javascript console followed by the following error: "Uncaught TypeError: Cannot read property 'seq' of undefined." This occurs when I go to the /my/todos route and also occurs when I create a new todo.

While using two browser windows at that same route and after the aforementioned error occurs, the newly created todo doesn't show up in the other window until after I create a todo (in the second browser window).

The error doesn't show up when I'm "offline".

**Comment by bajtos** [comment]
What is the stack trace of this uncaught error?

**Comment by boscodsouza82** [comment]
Is this error fixed? Is the stack trace still needed?

**Comment by osxi** [comment]
Closed because I don't remember the details. I can attempt to reproduce it if anybody wants, though.
