### ISSUE TITLE
none isomorphic data sync and error in datasources.local.js

### ISSUE THREAD

**Issue by rrNuvoPoint** [strongloop/loopback-example-offline-sync#66]
Hello!

I need a offline data sync to use in an ionic app so i need it to be none isomorphic. This loopback example is broken for me. Every time i use to different browsers on my local machine to make changes it make conflicts that cannot me resolved. 

Trying to resolve result in this:

<code>Error: Duplicate entry for LocalTodo.id</code>

Also i had to update:

<code>
module.exports = {
  remote: {
    url: GLOBAL_CONFIG.restApiUrl
  }
};
</code>

To 

<code>
module.exports = {
  remote: {
    url: 'http://localhost:3000'+GLOBAL_CONFIG.restApiUrl
  }
};
</code>

For it just to semi work with server sync.

Is there anyone who got a working example of loopback offline sync with none isomorphic code?

**Comment by bajtos** [comment]
Hi, could you please fetch the latest version from github and try again?
