### ISSUE TITLE
Request expects at least host or hostname, but none given in browser mode

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback-example-offline-sync#69]
The todo app's 'sync' button throws this error:

```
Uncaught Error: Invalid URI "/api/Todos/checkpoint"
```

And debugging I find that Request fails on this line:

```
if (!(self.uri.host || (self.uri.hostname && self.uri.port)) && !self.uri.isUnix) {
```

since we only call with a relative path.

Should it be necessary to make requests with an absolute uri? That would be silly for browsers, but if must for now, so be it...

**Comment by bajtos** [comment]
> Should it be necessary to make requests with an absolute uri? That would be silly for browsers, but if must for now, so be it...

Hmm, that's rather unfortunate :( Perhaps we can use `window.location.host` when running in a browser? Ideally this change should be made directly in the request module.

@Morriz would you mind submitting the patch yourself?

**Comment by Morriz** [comment]
Sure, when I have the time. I already realized that the Request repo is where it should go :)
