### ISSUE TITLE
To big for a web app?

### ISSUE THREAD

**Issue by jantimon** [strongloop/loopback-example-offline-sync#72]
I am investigating if loopback might work for me and I understand that this app is just a demo.
However what I found here scared me - In order to run this tiny todo app it takes mega bytes to download on the client.

I did the following steps:

cloned the repository
ran grunt
went to client/lbclient/
executed `du -sm browser.bundle.js`
Result 6MB (!!)

Is strongloop for phonegap apps only?

**Comment by superkhau** [comment]
I believe there are already feature requests in the LoopBack repo to reduce the size of the client bundle. See https://github.com/strongloop/loopback/issues/989.
