### ISSUE TITLE
Update app to have latest standard scaffolding

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-example-offline-sync#79]
This example needs to be updated per https://github.com/strongloop-internal/scrum-loopback/issues/495.

**Comment by davidcheung** [comment]
@crandmck https://github.com/strongloop/loopback-example-offline-sync/pull/73/files
it appears task has been done by someone else and is reflecting in master already :)

**Comment by crandmck** [comment]
Excellent, then our work here is done!
